
name: Pull and upload test collation

# We run this every day at 6am UTC, or else when called via Github
on:
  schedule: 
   - cron: '10 6 * * *'
  workflow_dispatch:
    inputs:
      forceCollate:
        description: "Force the full collation process to run"
        required: true 
        type: boolean
          
jobs:
  # Call the reusable workflow from DHUniWien/edition_tools.
  download-and-collate:
    name: Pull and collate all transcriptions
    uses: DHUniWien/edition-tools/.github/workflows/download-and-collate.yml@master
    with:
      forceCollate: ${{ inputs.forceCollate == true }}
      blockOnValidation: ${{ false }}
      xml_schema: transcription/tei-xml/tei_all.rng
      api_test_base: https://api.editions.byzantini.st/ChronicleMETest/stemmarest
      stemmaweb_user: chronicle@stemmaweb.net
      tradition_name: Ժամանակագրութիւն
      tradition_lang: Armenian
    secrets: inherit
   
